# construir um dockerfile para iniciar o servidor do frontend e instalar os pacotes
# procurar estrutura base do nextJS, utilizando os componentes com na pasta base src/
# adicionar os pacotes necessarios para utilizar react-hook-forms e zustand para controle de estado
# utilizar axios para controler as requisições para o backend
# instalar o tailwind css para criação dos componentes