from tests.fixtures.db_fixture import *
from tests.fixtures.user_fixture import *
from tests.fixtures.teacher_fixture import *
from tests.fixtures.learner_fixture import *
from tests.fixtures.user_config_fixture import *
from tests.fixtures.group_of_flashcard_by_teacher import *
from tests.fixtures.flashcard_basic_fixture import *
from tests.fixtures.flashcard_choose_fixture import *
from tests.fixtures.flashcard_multiple_choice_fixture import *