"""migração inicial

Revision ID: 22401466e7f7
Revises: 
Create Date: 2025-09-30 01:28:03.104667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22401466e7f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo de flashcard', sa.Enum('BASIC', 'CHOOSE', 'MULTIPLE_CHOICE', name='flashcardtypes'), nullable=False),
    sa.Column('é ativo?', sa.Boolean(), nullable=True),
    sa.Column('criado em', sa.DateTime(), nullable=True),
    sa.Column('ultima atualização', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_id'), 'flashcards', ['id'], unique=False)
    op.create_table('group_flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descrição', sa.String(), nullable=True),
    sa.Column('prazo para próxima revisão', sa.Date(), nullable=True),
    sa.Column('percentual memorizados?', sa.Integer(), nullable=True),
    sa.Column('é ativo?', sa.Boolean(), nullable=True),
    sa.Column('criado em', sa.DateTime(), nullable=True),
    sa.Column('ultima atualização', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_flashcards_id'), 'group_flashcards', ['id'], unique=False)
    op.create_table('group_flashcards_by_teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descrição', sa.String(), nullable=True),
    sa.Column('nivel de dificuldade', sa.Enum('DIFFICULT', 'MEDIUM', 'EASY', name='levelenum'), nullable=False),
    sa.Column('prazo para próxima revisão', sa.Date(), nullable=True),
    sa.Column('percentual memorizados?', sa.Integer(), nullable=True),
    sa.Column('é ativo?', sa.Boolean(), nullable=True),
    sa.Column('criado em', sa.DateTime(), nullable=True),
    sa.Column('ultima atualização', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_flashcards_by_teacher_id'), 'group_flashcards_by_teacher', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('nome completo', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('sexo', sa.Enum('MALE', 'FEMALE', 'OTHER', 'NONE', name='genderenum'), nullable=False),
    sa.Column('data de nascimento', sa.Date(), nullable=True),
    sa.Column('é ativo?', sa.Boolean(), nullable=True),
    sa.Column('criado em', sa.DateTime(), nullable=True),
    sa.Column('ultima atualização', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome completo')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_usuario'), 'users', ['usuario'], unique=True)
    op.create_table('usersconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modo escuro ativo?', sa.Boolean(), nullable=True),
    sa.Column('idioma', sa.Enum('PORTUGUESE_BR', 'ENGLISH', name='languageenum'), nullable=False),
    sa.Column('criado em', sa.DateTime(), nullable=True),
    sa.Column('ultima atualização', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersconfig_id'), 'usersconfig', ['id'], unique=False)
    op.create_table('flashcard_basic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frente', sa.String(), nullable=False),
    sa.Column('verso', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['flashcards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flashcard_choose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto base', sa.String(), nullable=False),
    sa.Column('palavras-chave', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['flashcards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flashcard_multiple_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.String(), nullable=False),
    sa.Column('resposta 1', sa.String(), nullable=False),
    sa.Column('resposta 2', sa.String(), nullable=False),
    sa.Column('resposta 3', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['flashcards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_flashcard_association',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('flashcard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group_flashcards.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'flashcard_id')
    )
    op.create_table('group_teacher_flashcard_association',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('flashcard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group_flashcards_by_teacher.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'flashcard_id')
    )
    op.create_table('memory_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.Column('group_type', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('total de flashcards acertados?', sa.Integer(), nullable=True),
    sa.Column('total de flashcards errados?', sa.Integer(), nullable=True),
    sa.Column('é ativo?', sa.Boolean(), nullable=True),
    sa.Column('criado em', sa.DateTime(), nullable=True),
    sa.Column('ultima atualização', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_game_id'), 'memory_game', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo de permissão', sa.Enum('GROUP_PUBLIC', 'GROUP_PRIVATE', name='typepermissionenum'), nullable=False),
    sa.Column('data limite de disponibilidade', sa.Date(), nullable=True),
    sa.Column('grupo de flashcards associado', sa.Integer(), nullable=False),
    sa.Column('é ativo?', sa.Boolean(), nullable=True),
    sa.Column('criado em', sa.DateTime(), nullable=True),
    sa.Column('ultima atualização', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['grupo de flashcards associado'], ['group_flashcards_by_teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.Column('total de flashcards acertados?', sa.Integer(), nullable=True),
    sa.Column('total de flashcards errados?', sa.Integer(), nullable=True),
    sa.Column('total de jogos finalizados?', sa.Integer(), nullable=True),
    sa.Column('total de grupos memorizados?', sa.Integer(), nullable=True),
    sa.Column('é ativo?', sa.Boolean(), nullable=True),
    sa.Column('criado em', sa.DateTime(), nullable=True),
    sa.Column('ultima atualização', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.Column('total de flashcards acertados?', sa.Integer(), nullable=True),
    sa.Column('total de flashcards errados?', sa.Integer(), nullable=True),
    sa.Column('total de jogos finalizados?', sa.Integer(), nullable=True),
    sa.Column('total de grupos memorizados?', sa.Integer(), nullable=True),
    sa.Column('é ativo?', sa.Boolean(), nullable=True),
    sa.Column('criado em', sa.DateTime(), nullable=True),
    sa.Column('ultima atualização', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    op.create_table('learners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.Integer(), nullable=False),
    sa.Column('total de flashcards acertados?', sa.Integer(), nullable=True),
    sa.Column('total de flashcards errados?', sa.Integer(), nullable=True),
    sa.Column('total de jogos finalizados?', sa.Integer(), nullable=True),
    sa.Column('total de grupos memorizados?', sa.Integer(), nullable=True),
    sa.Column('professor', sa.Integer(), nullable=False),
    sa.Column('é ativo?', sa.Boolean(), nullable=True),
    sa.Column('criado em', sa.DateTime(), nullable=True),
    sa.Column('ultima atualização', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['professor'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learners_id'), 'learners', ['id'], unique=False)
    op.create_table('student_group_flashcards',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_flashcards.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    op.create_table('teacher_group_flashcards',
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_flashcards_by_teacher.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], )
    )
    op.create_table('group_flashcards_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo de flashcards associado', sa.Integer(), nullable=False),
    sa.Column('prazo para próxima revisão', sa.Date(), nullable=True),
    sa.Column('percentual memorizados?', sa.Integer(), nullable=True),
    sa.Column('aprendiz', sa.Integer(), nullable=False),
    sa.Column('é ativo?', sa.Boolean(), nullable=True),
    sa.Column('criado em', sa.DateTime(), nullable=True),
    sa.Column('ultima atualização', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['aprendiz'], ['learners.id'], ),
    sa.ForeignKeyConstraint(['grupo de flashcards associado'], ['group_flashcards_by_teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_flashcards_progress_id'), 'group_flashcards_progress', ['id'], unique=False)
    op.create_table('permission_learners',
    sa.Column('learner_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission_learners')
    op.drop_index(op.f('ix_group_flashcards_progress_id'), table_name='group_flashcards_progress')
    op.drop_table('group_flashcards_progress')
    op.drop_table('teacher_group_flashcards')
    op.drop_table('student_group_flashcards')
    op.drop_index(op.f('ix_learners_id'), table_name='learners')
    op.drop_table('learners')
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_memory_game_id'), table_name='memory_game')
    op.drop_table('memory_game')
    op.drop_table('group_teacher_flashcard_association')
    op.drop_table('group_flashcard_association')
    op.drop_table('flashcard_multiple_choice')
    op.drop_table('flashcard_choose')
    op.drop_table('flashcard_basic')
    op.drop_index(op.f('ix_usersconfig_id'), table_name='usersconfig')
    op.drop_table('usersconfig')
    op.drop_index(op.f('ix_users_usuario'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_group_flashcards_by_teacher_id'), table_name='group_flashcards_by_teacher')
    op.drop_table('group_flashcards_by_teacher')
    op.drop_index(op.f('ix_group_flashcards_id'), table_name='group_flashcards')
    op.drop_table('group_flashcards')
    op.drop_index(op.f('ix_flashcards_id'), table_name='flashcards')
    op.drop_table('flashcards')
    # ### end Alembic commands ###
